### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by JaySmith502**
Adding CodePaLouSa to OutspokenWomen2018 table

### CODE REVIEW

**Comment by JaySmith502** [comment]
Would like to add CodePaLouSa to OutspokenWoman2018 CFP Table

**Comment by JaySmith502** [comment]
I clearly did something wrong

**Comment by tessak22** [comment]
No worries, just similar lines were grabbed at the same time. I resolved it and its been added. Thank you so much for your contribution.

**Comment by JaySmith502** [comment]
Oh, thanks!  Not sure I'll ever get the full hang of Github.  Hope this
helps somebody!

**Pull request merged**
